#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("quickmeal.Resource", IsApplication=true)]

namespace quickmeal
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int favRecipesArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int FRPLayout = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int RecipeItem = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int addButton = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int editText1 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int favouriteViewButton = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int fridgeListView = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int gridLayout1 = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int recipeDesc = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int recipeImage = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int recipeName = 2131099650;
			
			// aapt resource value: 0x7f06000a
			public const int recipefornowButton = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int showFridgeButton = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int textEditor = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int textMainView = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int FavRecipe = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FavRecipePreview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Fridge = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Fridge_x = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Recipe = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int favRecipePreviewTitle = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int favouriteViewButtonText = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int favouriteViewTitle = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int fridgeViewTitle = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int mainViewTitle = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int recipeViewTitle = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int recipefornowButtonText = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int showFridgeButtonText = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
